### ISSUE TITLE
没有可用的work, 不能运行测试

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-hazard#1]
![image](https://user-images.githubusercontent.com/28851617/91857669-c6a45a80-ec9a-11ea-98d3-075e26c1705a.png)

请问这个要怎么补数据？

**Comment by mao303mao** [comment]
你要去压测机管理页面，那里有下载已经编译好的worker端的程序，执行后面的命令。
主要要先启动etcd。
可以点击右下角的帮助，有简单说明。

**Comment by mao303mao** [comment]
> ![image](https://user-images.githubusercontent.com/28851617/91857669-c6a45a80-ec9a-11ea-98d3-075e26c1705a.png)
> 
> 请问这个要怎么补数据？

你要去压测机管理页面，那里有下载已经编译好的worker端的程序，执行后面的命令--注意提供etcd的ip。[]中的参数可以不提供，但你的机器ip不是192.168.*这种局域网的，就需要提供了（主要是通过etcd告诉master，worker的ip及端口.）主要要先启动etcd。
如果是用着玩玩（master、etcd、worker在一台机器上，默认127.0.0.1），也可以都不提供后面的参数。

可以点击右下角的帮助，有简单说明。

这里是采用etcd+grpc的分布式的处理，所以你可以在任意机器上使用下载好的worker端的程序执行上述命令。
如果你分布在不同的机器上，注意防火墙要关闭。
