### ISSUE TITLE
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-hazard#2]
【服务器：redhat7.2 】
ip是192.168.102.55
etcd驱动安装在（redhat7.2）:
etcd-v3.3.25-linux-amd64>./etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379

【客户端：win10】
boomerHazardServer驱动安装在win10：
boomerHazardServer.exe -EtcdAddr 192.168.102.55  -Host 192.168.102.55 -Port 8068    

【web页面】
![image](https://user-images.githubusercontent.com/28851617/91918826-ae622900-ecf6-11ea-91b6-a8565a2c24c6.png)

【报错】
site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1599006214.157088043","description":"Error received from peer ipv4:192.168.102.55:8068","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Stream removed","grpc_status":2}"
>
2020-09-02T00:23:34Z {'REMOTE_ADDR': '192.168.175.219', 'REMOTE_PORT': '9904', 'HTTP_HOST': '192.168.102.55:8089', (hidden keys: 28)} failed with _InactiveRpcError

**Comment by mao303mao** [comment]
boomerHazardServer.exe -EtcdAddr 192.168.102.55 -Host 192.168.102.55 -Port 8068 
说明一下：-Host -Port 其实是压测机，也就是你客户端这个grpc服务的ip和端口（也就是你win10机器的）。

这里我起名有歧义，不好意思（因为这里虽然是worker，但其实是个rpc服务。这里提供这两个参数主要是为了告诉etcd而已）
当然，按你这里的情况，-Host 192.168.102.55 -Port 8068 可以不提供

**Comment by mao303mao** [comment]
> 【服务器：redhat7.2 】
> ip是192.168.102.55
> etcd驱动安装在（redhat7.2）:
> etcd-v3.3.25-linux-amd64>./etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379
> 
> 【客户端：win10】
> boomerHazardServer驱动安装在win10：
> boomerHazardServer.exe -EtcdAddr 192.168.102.55 -Host 192.168.102.55 -Port 8068
> 
> 【web页面】
> ![image](https://user-images.githubusercontent.com/28851617/91918826-ae622900-ecf6-11ea-91b6-a8565a2c24c6.png)
> 
> 【报错】
> site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
> raise _InactiveRpcError(state)
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> status = StatusCode.UNKNOWN
> details = "Stream removed"
> debug_error_string = "{"created":"@1599006214.157088043","description":"Error received from peer ipv4:192.168.102.55:8068","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Stream removed","grpc_status":2}"
> 
> > 
> 
> 2020-09-02T00:23:34Z {'REMOTE_ADDR': '192.168.175.219', 'REMOTE_PORT': '9904', 'HTTP_HOST': '192.168.102.55:8089', (hidden keys: 28)} failed with _InactiveRpcError

boomerHazardServer.exe -EtcdAddr 192.168.102.55 -Host 192.168.102.55 -Port 8068
说明一下：-Host -Port 其实是压测机，也就是你客户端这个grpc服务的ip和端口（也就是你win10机器的）。

这里我起名有歧义，不好意思（因为这里虽然是worker，但其实是个rpc服务。这里提供这两个参数主要是为了告诉etcd而已）
当然，按你这里的情况，-Host 192.168.102.55 -Port 8068 可以不提供
