### ISSUE TITLE
Prometheus+Grafana+ locust-hazard数据持久化是否可以实现

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-hazard#3]
## 【前言】

> 谢谢作者的解答，
> 之前的2个问题，我这边基本已经解决。‘
>
> 对项目理解不清楚，请担待、包含。

【使用心得】
1，项目不能跨域。意思：boomerHazardServer.exe（win10） 在其他机器上面运行，就报这个现象[https://github.com/mao303mao/locust-hazard/issues/2]

2，（linux部署）boomerHazardServer、etcd、locust都必须部署在同一台机器上。

## 【疑问】

1，总请求数怎么控制,例如：时间30s，只想并发3W的总请求数；
2，并发速度与时间怎么控制；

## 【bug】

- 复现路径：事务管理页面，重置，新录入数据-》保存-》执行-》时时/统计情况页面，展示的数据还是tmp.json上次历史数据，这里尝试多次依然复现。

- 暂时解决方法:【要想是最新数据】==需要新录入-》然后导入-》执行）==

## 【期望】

```
1，Prometheus+Grafana+ locust-hazard数据持久化怎么实现呢？
2，前端项目开源
```

**Comment by mao303mao** [comment]
1-可以跨域，3者之间网络能通就可以--注意防火墙要关闭。
上面那个错误时因为boomerHazardServer 指定host参数时，是他（boomerHazardServer所在机器）ip，而不是locusthazard所在机器的ip，rRPC服务调用错误的地址所致。 我们这里就是etcd+locusthazard在一台机器上，其他woker（也就是boomerHazardServer ）分布在其他各个机器上，实现很方便的压测机扩展，进行超大压力测试。
2-孵化率指的是每秒增加用户数，你想实现30s，3w：用户数：3w，可以孵化率1000，运行60s即可。
这样前30s，压测数慢慢加到3w，后30s就以3w用户进行压测了。
如果你不怕机器爆掉，孵化率再设置大点。
3-bug是因为原版locust会保存上次记录，我没有去改动，因为要去修改原版locust源码，locust目前还在不断更新，等他到一个稳定版本后去处理。
所以我放开重置统计这个处理，随时可以点击清理，可以清除上次的运行记录来处理，而原版只能在运行中使用。
推荐用法：重置压测机->保存/导入场景->更新压测机->新的测试
4-这里是个半框架性质的，好多功能可以添加和，只是目前我们这里需求可以满足了，就没再增加了。
   这里前端、后端都开源了，master中是locust改版的部分（前端代码也在里面），woker是boomerHazardServer的源码，你可以按需编译成windows/linux端的
5-Prometheus+Grafana 这块很简单，我暂时还没加上。你其实可以去实现，参考这里去修改newWeb.py即可。
https://github.com/myzhan/boomer/blob/master/prometheus_exporter.py
