### ISSUE TITLE
响应断言功能这里，增加api返回状态码该怎么新增断言脚本

### ISSUE THREAD

**Issue by huanjoyous** [mao303mao/locust-hazard#4]
## 【前言】

> 谢谢作者的解答，
> 
>对项目理解不清楚，请担待、包含。

## 【场景】

> 通过请求接口（get/post）返回接口如下。返回http状态码=200，想断言status这个key，如果status不等于0，记录在失败情况页面
>
> ```json
> {
>     "status": "0",
>     "message": "正确",
>     "result": [
>         {
>             "data": "xxxx"
>         }
>     ]
> }
> ```

目前我这边代码写死了status不等于0干预不带方便，业务场景不止status=0这一种场景，获取data方法是切片进行到得。（小小测试一枚，见谅）

```go
		jsonStr:=resp.String()
		var dat map[string]interface{}
		if err := json.Unmarshal([]byte(jsonStr), &dat); err == nil {
			//fmt.Println("==============json str 转map=======================")
			//fmt.Println(dat)
			//msg_error :=("错误码:")
			msg_status:=(dat["status"])
			msg_eq_status:=("0")
			//fmt.Println(aa)
			//fmt.Println(msg_error,aa)
			if msg_status != msg_eq_status {
				gBoomer.RecordFailure("http", testTask.GetTaskName(), responseTime, fmt.Sprintf("status状态码不为0,实际返回的状态码:%s，实际返回结果为:%s", msg_status,resp))
				return
			}
			//data := strings.Split((string(jsonStr)), "data")[1]
			//fmt.Println((data[3:67]))
			}
```

### 【疑问】

```go
// 执行判断，因为是压力测试，所以判断就简单粗暴一点:状态码或者内容长度
func DoAssertActionChains(resp *grequests.Response, assertActionChain []*proto.InitBommerRequest_AssertAction) (bool, string) {
	respLength := len(resp.Bytes())
	for _, assertAction := range assertActionChain {
		switch assertAction.AssertType {
		case 0:
			{
				if resp.StatusCode != int(assertAction.RuleValue) {
					if resp.StatusCode>=300 && resp.StatusCode<400{
						return false, fmt.Sprintf("请求判断有误,响应码是[%d],期望[%d]" +
							"重定向到[%s]", resp.StatusCode, assertAction.RuleValue,resp.Header.Get("Location"))
					}
					return false, fmt.Sprintf("请求判断有误,响应码是[%d],期望[%d]", resp.StatusCode, assertAction.RuleValue)
				}
				continue
			}
            .....
```

> assertAction.RuleValue里面看不懂，好像是通过protoc.exe执行生成的？？？
>

# 【期望】

```
新增自定义api接口josn返回断言
```

**Comment by mao303mao** [comment]
assertAction.RuleValue 是proto工具生成的。
因为压力测试和接口测试不一样，关注的是服务端的处理及响应能力，所以我断言这里简单粗暴了：判断响应码和响应的内容的字节码长度了--因为服务端异常情况和正常情况，响应内容长度都是相差较大的，个人以为大部分情况可以满足的
-------------------------------------------------------------------------------------------------------------
前置处理中有各种保存参数的方法，包括xpath解析html,json解析,正则匹配等等。
将这里保存参数那里的代码挪到断言的地方改改就可以了，说到底还是我偷懒。
后面找个时间将这部分功能加上吧

**Comment by huanjoyous** [comment]
> ## assertAction.RuleValue是proto工具生成的。
> 因为压力测试和接口测试不一样，关注的是服务端的处理以及响应能力，所以我断言这里简单粗暴了：确定响应码和响应的内容的字节码长度了- -因为服务端异常情况和正常情况，响应内容长度都是相差延迟的，个人以为大部分情况可以满足的
> 前置处理中有各种保存参数的方法，包括XPath的解析HTML，JSON解析，正则匹配等等。
> 将这里保存参数那里的代码挪到断言的地方改改就可以了，说到底还是我偷懒。
> 后面找个时间将这部分功能加上吧


谢谢作者您的提示，移植前置处理中的方式，已经实现。

期待作者持久更新项目，可以的话帮忙加上数据持久化。

**Comment by mao303mao** [comment]
最近原版locust变化有点大，而且有bug。等他下个稳定的版本的时候，这里会作对应的调整。到时加上持久化的功能。
其实很简单，将指标数据推送到一个时序数据库就可以了。
